version: '3.7'
services:
  eureka:
    image: localhost:5000/sourabhh/eureka-server:PACKT-SNAPSHOT
    ports:
      - "8761:8761"

  config:
    image: localhost:5000/sourabhh/config-server:PACKT-SNAPSHOT
    ports:
      - "8888:8888"

  restaurant-service:
    image: localhost:5000/sourabhh/restaurant-service:PACKT-SNAPSHOT
    ports:
      - "8080:8080"
    links:
      - eureka
      - config

  booking-service:
    image: localhost:5000/sourabhh/booking-service:PACKT-SNAPSHOT
    ports:
      - "8081:8080"
    links:
      - eureka
      - config

  user-service:
    image: localhost:5000/sourabhh/user-service:PACKT-SNAPSHOT
    restart: on-failure
    ports:
      - "8082:8080"
    depends_on:
      - eureka
      - config

